name: BFG Repo-Cleaner

on:
  push:
    branches:
      - master

jobs:
  bfg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download BFG JAR
        run: wget https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar bfg.jar

      - name: Run BFG
        run: java -jar bfg.jar --replace-text secret.txt

      - name: Cleanup BFG JAR
        run: rm bfg.jar
